In [1]:
from tfidfmatcher import Matcher
from parser import Parser

Error reading PDF: [Errno 2] No such file or directory: 'resumes/INFORMATION-TECHNOLOGY/10089434.pdf'
None


[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/srimanselvakumaran/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/srimanselvakumaran/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
seta = [["1", "2", "3", "4", "5", "6"],
        ["7", "8", "9", "10", "11", "12"],
        ["13", "14", "15", "16", "17", "18"],
        ["19", "20", "21", "22", "23", "24"],
        ["25", "26", "27", "28", "29", "30"],
        ["31", "32", "33", "34", "35", "36"],
        ["37", "38", "39", "40", "41", "42"],
        ["43", "44", "45", "46", "47", "48"]]

setb = [["1", "19", "10", "45", "5", "6"],
        ["32", "8", "9", "13", "11", "4"],
        ["22", "14", "40", "16", "17", "12"],
        ["19", "20", "18", "26", "23", "43"],
        ["25", "34", "27", "21", "44", "30"],
        ["28", "32", "33", "40", "35", "8"],
        ["13", "38", "31", "44", "41", "42"],
        ["43", "3", "39", "46", "27", "48"]]

In [3]:
matcher = Matcher()
matcher.fit(seta, setb)

In [4]:
import numpy as np
for a in seta:
  corp = matcher.student_dict.doc2bow(a)
  print(matcher.X @ Matcher.to_vec(matcher.student_model, corp, matcher.num_words).reshape(-1))

[1.         0.         0.         0.16666667 0.         0.
 0.         0.        ]
[0.         1.         0.         0.         0.         0.33333333
 0.16666667 0.        ]
[0.         0.         1.         0.         0.         0.16666667
 0.         0.        ]
[0.         0.         0.         0.83333333 0.16666667 0.
 0.         0.16666667]
[0.         0.         0.         0.         0.83333333 0.16666667
 0.16666667 0.16666667]
[0.         0.         0.         0.         0.         0.33333333
 0.66666667 0.        ]
[0.         0.         0.         0.         0.         0.
 0.         0.66666667]
[0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
for a in seta:
  print(matcher.predict(a))

[0 3 6 4 2]
[1 5 6 3 0]
[2 5 3 6 0]
[3 4 7 6 5]
[4 7 6 5 0]
[6 5 3 0 4]
[7 5 6 0 4]
[5 3 6 0 4]


/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2182: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)
/opt/homebrew/lib/python3.11/site-p